name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2', '3.3', '3.4']
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4.2.2
      - name: 'Set Up Ruby Environment'
        uses: ruby/setup-ruby@v1.186.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: 'Run Tests'
        run: bundle exec rake
